//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitCandy.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitCandy.App_GlobalResources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with this username already exists..
        /// </summary>
        public static string Account_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove yourself.
        /// </summary>
        public static string Account_CantRemoveSelf {
            get {
                return ResourceManager.GetString("Account_CantRemoveSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Account_ChangePasswordTitle {
            get {
                return ResourceManager.GetString("Account_ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform Password.
        /// </summary>
        public static string Account_ConformPassword {
            get {
                return ResourceManager.GetString("Account_ConformPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_CreateTitle {
            get {
                return ResourceManager.GetString("Account_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_CreationUnsuccessfull {
            get {
                return ResourceManager.GetString("Account_CreationUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform Delete User {0}.
        /// </summary>
        public static string Account_DeleteTitle {
            get {
                return ResourceManager.GetString("Account_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to delete the account &quot;{0}&quot;?.
        /// </summary>
        public static string Account_DeletionWords {
            get {
                return ResourceManager.GetString("Account_DeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Account_Description {
            get {
                return ResourceManager.GetString("Account_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0}.
        /// </summary>
        public static string Account_DetailTitle {
            get {
                return ResourceManager.GetString("Account_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User {0}.
        /// </summary>
        public static string Account_EditTitle {
            get {
                return ResourceManager.GetString("Account_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with this email already exists..
        /// </summary>
        public static string Account_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Account_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot username or password.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Account_ForgotTitle {
            get {
                return ResourceManager.GetString("Account_ForgotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is system administrator.
        /// </summary>
        public static string Account_IsSystemAdministrator {
            get {
                return ResourceManager.GetString("Account_IsSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Users.
        /// </summary>
        public static string Account_ListTitle {
            get {
                return ResourceManager.GetString("Account_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password error.
        /// </summary>
        public static string Account_LoginFailed {
            get {
                return ResourceManager.GetString("Account_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Account_LoginTitle {
            get {
                return ResourceManager.GetString("Account_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Account_NewPassword {
            get {
                return ResourceManager.GetString("Account_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Account_Nickname {
            get {
                return ResourceManager.GetString("Account_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Account_OldPassword {
            get {
                return ResourceManager.GetString("Account_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password error.
        /// </summary>
        public static string Account_OldPasswordError {
            get {
                return ResourceManager.GetString("Account_OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password error.
        /// </summary>
        public static string Account_PasswordError {
            get {
                return ResourceManager.GetString("Account_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respositories.
        /// </summary>
        public static string Account_Repositories {
            get {
                return ResourceManager.GetString("Account_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH.
        /// </summary>
        public static string Account_SSH {
            get {
                return ResourceManager.GetString("Account_SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Key.
        /// </summary>
        public static string Account_SshKeys {
            get {
                return ResourceManager.GetString("Account_SshKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Account_Teams {
            get {
                return ResourceManager.GetString("Account_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_UpdateUnsuccessfull {
            get {
                return ResourceManager.GetString("Account_UpdateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Account_Username {
            get {
                return ResourceManager.GetString("Account_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string Account_UsernameOrEmail {
            get {
                return ResourceManager.GetString("Account_UsernameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} user(s) found.
        /// </summary>
        public static string Account_UsersFound {
            get {
                return ResourceManager.GetString("Account_UsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitCandy&amp;copy; is a [Git](http://git-scm.com/documentation) distributed version control platform based on ASP.NET MVC application, which supports public and private repositories. You can create and collaborate your repository with your team anytime anywhere without any limit.
        ///
        ///Visit a demo on [http://gitcandy.com](http://gitcandy.com)
        ///
        ///Get source and fork me on [http://github.com/Aimeast/GitCandy](http://github.com/Aimeast/GitCandy)
        ///
        ///---
        ///#### Thanks for (alphabet).
        /// </summary>
        public static string Home_AboutDescription {
            get {
                return ResourceManager.GetString("Home_AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Home_AboutTitle {
            get {
                return ResourceManager.GetString("Home_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahead.
        /// </summary>
        public static string Repository_Ahead {
            get {
                return ResourceManager.GetString("Repository_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read for anonymous.
        /// </summary>
        public static string Repository_AllowAnonymousRead {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write for anonymous.
        /// </summary>
        public static string Repository_AllowAnonymousWrite {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository with this name already exists..
        /// </summary>
        public static string Repository_AlreadyExists {
            get {
                return ResourceManager.GetString("Repository_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authored at.
        /// </summary>
        public static string Repository_AuthoredAt {
            get {
                return ResourceManager.GetString("Repository_AuthoredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base branch.
        /// </summary>
        public static string Repository_BaseBranch {
            get {
                return ResourceManager.GetString("Repository_BaseBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to behind.
        /// </summary>
        public static string Repository_Behind {
            get {
                return ResourceManager.GetString("Repository_Behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a binary file that preview is not supported.
        /// </summary>
        public static string Repository_BinaryFileWrods {
            get {
                return ResourceManager.GetString("Repository_BinaryFileWrods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blame.
        /// </summary>
        public static string Repository_Blame {
            get {
                return ResourceManager.GetString("Repository_Blame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} at {1} · {0}.
        /// </summary>
        public static string Repository_BlameTitle {
            get {
                return ResourceManager.GetString("Repository_BlameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} at {1} · {0}.
        /// </summary>
        public static string Repository_BlobTitle {
            get {
                return ResourceManager.GetString("Repository_BlobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to delete the branch &quot;{0}&quot;?.
        /// </summary>
        public static string Repository_BranchDeletionWords {
            get {
                return ResourceManager.GetString("Repository_BranchDeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Repository_Branches {
            get {
                return ResourceManager.GetString("Repository_Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches · {0}.
        /// </summary>
        public static string Repository_BranchesTitle {
            get {
                return ResourceManager.GetString("Repository_BranchesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary: {0} changed files with {1} additions and {2} deletions..
        /// </summary>
        public static string Repository_ChangedSummary {
            get {
                return ResourceManager.GetString("Repository_ChangedSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborations.
        /// </summary>
        public static string Repository_Collaborations {
            get {
                return ResourceManager.GetString("Repository_Collaborations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborations · {0}.
        /// </summary>
        public static string Repository_CollaborationTitle {
            get {
                return ResourceManager.GetString("Repository_CollaborationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborators.
        /// </summary>
        public static string Repository_Collaborators {
            get {
                return ResourceManager.GetString("Repository_Collaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits.
        /// </summary>
        public static string Repository_Commits {
            get {
                return ResourceManager.GetString("Repository_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History for {1} · {0}.
        /// </summary>
        public static string Repository_CommitsTitle {
            get {
                return ResourceManager.GetString("Repository_CommitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to committed at.
        /// </summary>
        public static string Repository_CommittedAt {
            get {
                return ResourceManager.GetString("Repository_CommittedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} at {1} · {0}.
        /// </summary>
        public static string Repository_CommitTitle {
            get {
                return ResourceManager.GetString("Repository_CommitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Repository_Compare {
            get {
                return ResourceManager.GetString("Repository_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to compare.
        /// </summary>
        public static string Repository_CompareNothing {
            get {
                return ResourceManager.GetString("Repository_CompareNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare · {0}.
        /// </summary>
        public static string Repository_CompareTitle {
            get {
                return ResourceManager.GetString("Repository_CompareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Repository_Contributors {
            get {
                return ResourceManager.GetString("Repository_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors · {0}.
        /// </summary>
        public static string Repository_ContributorsTitle {
            get {
                return ResourceManager.GetString("Repository_ContributorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Repository_Copied {
            get {
                return ResourceManager.GetString("Repository_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Repository_CopyToClipboard {
            get {
                return ResourceManager.GetString("Repository_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Repository.
        /// </summary>
        public static string Repository_CreateTitle {
            get {
                return ResourceManager.GetString("Repository_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_CreationUnsuccessfull {
            get {
                return ResourceManager.GetString("Repository_CreationUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current branch.
        /// </summary>
        public static string Repository_CurrentBranch {
            get {
                return ResourceManager.GetString("Repository_CurrentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits in current branch.
        /// </summary>
        public static string Repository_CurrentCommits {
            get {
                return ResourceManager.GetString("Repository_CurrentCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors in current branch.
        /// </summary>
        public static string Repository_CurrentContributors {
            get {
                return ResourceManager.GetString("Repository_CurrentContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files in current branch.
        /// </summary>
        public static string Repository_CurrentFiles {
            get {
                return ResourceManager.GetString("Repository_CurrentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source size in current branch.
        /// </summary>
        public static string Repository_CurrentSourceSize {
            get {
                return ResourceManager.GetString("Repository_CurrentSourceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default branch.
        /// </summary>
        public static string Repository_DefaultBranch {
            get {
                return ResourceManager.GetString("Repository_DefaultBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits in default branch.
        /// </summary>
        public static string Repository_DefaultCommits {
            get {
                return ResourceManager.GetString("Repository_DefaultCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors in default branch.
        /// </summary>
        public static string Repository_DefaultContributors {
            get {
                return ResourceManager.GetString("Repository_DefaultContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files in default branch.
        /// </summary>
        public static string Repository_DefaultFiles {
            get {
                return ResourceManager.GetString("Repository_DefaultFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source size in default branch.
        /// </summary>
        public static string Repository_DefaultSourceSize {
            get {
                return ResourceManager.GetString("Repository_DefaultSourceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform Delete Repository {0}.
        /// </summary>
        public static string Repository_DeleteTitle {
            get {
                return ResourceManager.GetString("Repository_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to delete the repository &quot;{0}&quot;?.
        /// </summary>
        public static string Repository_DeletionWords {
            get {
                return ResourceManager.GetString("Repository_DeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Repository_Description {
            get {
                return ResourceManager.GetString("Repository_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository {0}.
        /// </summary>
        public static string Repository_DetailTitle {
            get {
                return ResourceManager.GetString("Repository_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Repository {0}.
        /// </summary>
        public static string Repository_EditTitle {
            get {
                return ResourceManager.GetString("Repository_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a empty repository or we are importing a remote repository. Push a repository with HEAD(master) branch for display here..
        /// </summary>
        public static string Repository_EmptyWords {
            get {
                return ResourceManager.GetString("Repository_EmptyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Repository_FileAdded {
            get {
                return ResourceManager.GetString("Repository_FileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Repository_FileCopied {
            get {
                return ResourceManager.GetString("Repository_FileCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Repository_FileDeleted {
            get {
                return ResourceManager.GetString("Repository_FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string Repository_FileIgnored {
            get {
                return ResourceManager.GetString("Repository_FileIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Repository_FileModified {
            get {
                return ResourceManager.GetString("Repository_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed.
        /// </summary>
        public static string Repository_FileRenamed {
            get {
                return ResourceManager.GetString("Repository_FileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeChanged.
        /// </summary>
        public static string Repository_FileTypeChanged {
            get {
                return ResourceManager.GetString("Repository_FileTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmodified.
        /// </summary>
        public static string Repository_FileUnmodified {
            get {
                return ResourceManager.GetString("Repository_FileUnmodified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untracked.
        /// </summary>
        public static string Repository_FileUntracked {
            get {
                return ResourceManager.GetString("Repository_FileUntracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Url.
        /// </summary>
        public static string Repository_GitUrl {
            get {
                return ResourceManager.GetString("Repository_GitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HEAD has not set yet.
        /// </summary>
        public static string Repository_HeadNotSet {
            get {
                return ResourceManager.GetString("Repository_HeadNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Repository_History {
            get {
                return ResourceManager.GetString("Repository_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History for ·.
        /// </summary>
        public static string Repository_HistoryFor {
            get {
                return ResourceManager.GetString("Repository_HistoryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to initialize.
        /// </summary>
        public static string Repository_HowInit {
            get {
                return ResourceManager.GetString("Repository_HowInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Repository_Import {
            get {
                return ResourceManager.GetString("Repository_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support http(s) protocol only.
        /// </summary>
        public static string Repository_ImportTips {
            get {
                return ResourceManager.GetString("Repository_ImportTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a private repository.
        /// </summary>
        public static string Repository_IsPrivate {
            get {
                return ResourceManager.GetString("Repository_IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Repositories.
        /// </summary>
        public static string Repository_ListTitle {
            get {
                return ResourceManager.GetString("Repository_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name.
        /// </summary>
        public static string Repository_Name {
            get {
                return ResourceManager.GetString("Repository_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal view.
        /// </summary>
        public static string Repository_NormalView {
            get {
                return ResourceManager.GetString("Repository_NormalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found.
        /// </summary>
        public static string Repository_NoTags {
            get {
                return ResourceManager.GetString("Repository_NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent(s).
        /// </summary>
        public static string Repository_Parents {
            get {
                return ResourceManager.GetString("Repository_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular repositories.
        /// </summary>
        public static string Repository_PopularRepositories {
            get {
                return ResourceManager.GetString("Repository_PopularRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Repository_Raw {
            get {
                return ResourceManager.GetString("Repository_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Repository_Relationship {
            get {
                return ResourceManager.GetString("Repository_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url of remote repository.
        /// </summary>
        public static string Repository_RemoteUrlTitle {
            get {
                return ResourceManager.GetString("Repository_RemoteUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository size.
        /// </summary>
        public static string Repository_RepositorySize {
            get {
                return ResourceManager.GetString("Repository_RepositorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Repository_ShortAllowRead {
            get {
                return ResourceManager.GetString("Repository_ShortAllowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Repository_ShortAllowWrite {
            get {
                return ResourceManager.GetString("Repository_ShortAllowWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Repository_ShortIsOwner {
            get {
                return ResourceManager.GetString("Repository_ShortIsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Repository_ShortNonAllowRead {
            get {
                return ResourceManager.GetString("Repository_ShortNonAllowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Repository_ShortNonAllowWrite {
            get {
                return ResourceManager.GetString("Repository_ShortNonAllowWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Repository_ShortNotOwner {
            get {
                return ResourceManager.GetString("Repository_ShortNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Repository_Statistics {
            get {
                return ResourceManager.GetString("Repository_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to delete the tag &quot;{0}&quot;?.
        /// </summary>
        public static string Repository_TagDeletionWords {
            get {
                return ResourceManager.GetString("Repository_TagDeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Repository_Tags {
            get {
                return ResourceManager.GetString("Repository_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags · {0}.
        /// </summary>
        public static string Repository_TagsTitle {
            get {
                return ResourceManager.GetString("Repository_TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Repository_Teams {
            get {
                return ResourceManager.GetString("Repository_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string Repository_Tree {
            get {
                return ResourceManager.GetString("Repository_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} at {1} · {0}.
        /// </summary>
        public static string Repository_TreeTitle {
            get {
                return ResourceManager.GetString("Repository_TreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_UpdateUnsuccessfull {
            get {
                return ResourceManager.GetString("Repository_UpdateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Repository_Zip {
            get {
                return ResourceManager.GetString("Repository_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip with CR (\r).
        /// </summary>
        public static string Repository_ZipCR {
            get {
                return ResourceManager.GetString("Repository_ZipCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip with CRLF (\r\n).
        /// </summary>
        public static string Repository_ZipCRLF {
            get {
                return ResourceManager.GetString("Repository_ZipCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip with LF (\n).
        /// </summary>
        public static string Repository_ZipLF {
            get {
                return ResourceManager.GetString("Repository_ZipLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow register user.
        /// </summary>
        public static string Setting_AllowRegisterUser {
            get {
                return ResourceManager.GetString("Setting_AllowRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow repository creation.
        /// </summary>
        public static string Setting_AllowRepositoryCreation {
            get {
                return ResourceManager.GetString("Setting_AllowRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of cache directory.
        /// </summary>
        public static string Setting_CachePath {
            get {
                return ResourceManager.GetString("Setting_CachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting_EditTitle {
            get {
                return ResourceManager.GetString("Setting_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSH.
        /// </summary>
        public static string Setting_EnableSsh {
            get {
                return ResourceManager.GetString("Setting_EnableSsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force HTTPS connection.
        /// </summary>
        public static string Setting_ForceSsl {
            get {
                return ResourceManager.GetString("Setting_ForceSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of git core.
        /// </summary>
        public static string Setting_GitCorePath {
            get {
                return ResourceManager.GetString("Setting_GitCorePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is public server.
        /// </summary>
        public static string Setting_IsPublicServer {
            get {
                return ResourceManager.GetString("Setting_IsPublicServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local skip custom error.
        /// </summary>
        public static string Setting_LocalSkipCustomError {
            get {
                return ResourceManager.GetString("Setting_LocalSkipCustomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of commits per page.
        /// </summary>
        public static string Setting_NumberOfCommitsPerPage {
            get {
                return ResourceManager.GetString("Setting_NumberOfCommitsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items per list.
        /// </summary>
        public static string Setting_NumberOfItemsPerList {
            get {
                return ResourceManager.GetString("Setting_NumberOfItemsPerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of repository contributors.
        /// </summary>
        public static string Setting_NumberOfRepositoryContributors {
            get {
                return ResourceManager.GetString("Setting_NumberOfRepositoryContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-generate ssh key.
        /// </summary>
        public static string Setting_ReGenSsh {
            get {
                return ResourceManager.GetString("Setting_ReGenSsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform to Re-generate ssh key.
        /// </summary>
        public static string Setting_ReGenSshTitle {
            get {
                return ResourceManager.GetString("Setting_ReGenSshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to Re-generate ssh key?.
        /// </summary>
        public static string Setting_ReGenSshWords {
            get {
                return ResourceManager.GetString("Setting_ReGenSshWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of repositories.
        /// </summary>
        public static string Setting_RepositoryPath {
            get {
                return ResourceManager.GetString("Setting_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform to restart.
        /// </summary>
        public static string Setting_RestartTitle {
            get {
                return ResourceManager.GetString("Setting_RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to restart this application?.
        /// </summary>
        public static string Setting_RestartWords {
            get {
                return ResourceManager.GetString("Setting_RestartWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH connection port.
        /// </summary>
        public static string Setting_SshPort {
            get {
                return ResourceManager.GetString("Setting_SshPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS connection port.
        /// </summary>
        public static string Setting_SslPort {
            get {
                return ResourceManager.GetString("Setting_SslPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update settings was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Setting_UpdateSettingsUnsuccessfull {
            get {
                return ResourceManager.GetString("Setting_UpdateSettingsUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Shared_About {
            get {
                return ResourceManager.GetString("Shared_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Shared_Add {
            get {
                return ResourceManager.GetString("Shared_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitCandy.
        /// </summary>
        public static string Shared_AppTitle {
            get {
                return ResourceManager.GetString("Shared_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Shared_Back {
            get {
                return ResourceManager.GetString("Shared_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform.
        /// </summary>
        public static string Shared_Conform {
            get {
                return ResourceManager.GetString("Shared_Conform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Shared_Create {
            get {
                return ResourceManager.GetString("Shared_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Shared_Delete {
            get {
                return ResourceManager.GetString("Shared_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Shared_Detail {
            get {
                return ResourceManager.GetString("Shared_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Shared_Edit {
            get {
                return ResourceManager.GetString("Shared_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Shared_Generate {
            get {
                return ResourceManager.GetString("Shared_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanuages.
        /// </summary>
        public static string Shared_Lanuages {
            get {
                return ResourceManager.GetString("Shared_Lanuages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Shared_Login {
            get {
                return ResourceManager.GetString("Shared_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Shared_Logout {
            get {
                return ResourceManager.GetString("Shared_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Shared_No {
            get {
                return ResourceManager.GetString("Shared_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Shared_None {
            get {
                return ResourceManager.GetString("Shared_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Shared_Register {
            get {
                return ResourceManager.GetString("Shared_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Shared_Remove {
            get {
                return ResourceManager.GetString("Shared_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Shared_Repositories {
            get {
                return ResourceManager.GetString("Shared_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Shared_Reset {
            get {
                return ResourceManager.GetString("Shared_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Shared_Restart {
            get {
                return ResourceManager.GetString("Shared_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Shared_Save {
            get {
                return ResourceManager.GetString("Shared_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Shared_Search {
            get {
                return ResourceManager.GetString("Shared_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Shared_Settings {
            get {
                return ResourceManager.GetString("Shared_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong.
        /// </summary>
        public static string Shared_SomethingWrong {
            get {
                return ResourceManager.GetString("Shared_SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Shared_Teams {
            get {
                return ResourceManager.GetString("Shared_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - GitCandy.
        /// </summary>
        public static string Shared_TitleFormat {
            get {
                return ResourceManager.GetString("Shared_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Shared_Users {
            get {
                return ResourceManager.GetString("Shared_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Shared_Yes {
            get {
                return ResourceManager.GetString("Shared_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with this name already exists..
        /// </summary>
        public static string Team_AlreadyExists {
            get {
                return ResourceManager.GetString("Team_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Users for Team {0}.
        /// </summary>
        public static string Team_ChooseUserTitle {
            get {
                return ResourceManager.GetString("Team_ChooseUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Team.
        /// </summary>
        public static string Team_CreationTitle {
            get {
                return ResourceManager.GetString("Team_CreationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Team_CreationUnsuccessfull {
            get {
                return ResourceManager.GetString("Team_CreationUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform Delete Team {0}.
        /// </summary>
        public static string Team_DeleteTitle {
            get {
                return ResourceManager.GetString("Team_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you conform to delete the team &quot;{0}&quot;?.
        /// </summary>
        public static string Team_DeletionWords {
            get {
                return ResourceManager.GetString("Team_DeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team description.
        /// </summary>
        public static string Team_Description {
            get {
                return ResourceManager.GetString("Team_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0}.
        /// </summary>
        public static string Team_DetailTitle {
            get {
                return ResourceManager.GetString("Team_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Team {0}.
        /// </summary>
        public static string Team_EditTitle {
            get {
                return ResourceManager.GetString("Team_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Teams.
        /// </summary>
        public static string Team_ListTitle {
            get {
                return ResourceManager.GetString("Team_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Team_Members {
            get {
                return ResourceManager.GetString("Team_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string Team_Name {
            get {
                return ResourceManager.GetString("Team_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Team_Repositories {
            get {
                return ResourceManager.GetString("Team_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Team_ShortAdministrator {
            get {
                return ResourceManager.GetString("Team_ShortAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Team_ShortNonAdministrator {
            get {
                return ResourceManager.GetString("Team_ShortNonAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} team(s) found.
        /// </summary>
        public static string Team_TeamsFound {
            get {
                return ResourceManager.GetString("Team_TeamsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Team_UpdateUnsuccessfull {
            get {
                return ResourceManager.GetString("Team_UpdateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; and &quot;{1}&quot; must have the same value.
        /// </summary>
        public static string Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid email address.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid &quot;{1}&quot; file path.
        /// </summary>
        public static string Validation_Filepath {
            get {
                return ResourceManager.GetString("Validation_Filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; not a valid.
        /// </summary>
        public static string Validation_Name {
            get {
                return ResourceManager.GetString("Validation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be between {1} and {2}.
        /// </summary>
        public static string Validation_NumberRange {
            get {
                return ResourceManager.GetString("Validation_NumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is mandatory.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be smaller than {1} chars.
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be smaller than {1} chars and large then {2} chars.
        /// </summary>
        public static string Validation_StringLengthRange {
            get {
                return ResourceManager.GetString("Validation_StringLengthRange", resourceCulture);
            }
        }
    }
}
